### ISSUE TITLE
AdsToJava Maven version mismatch

### ISSUE THREAD

**Issue by robertsonj3** [Beckhoff/AdsToJava#4]
When building the AdsToJava library, the latest version of Maven is not compatible with the POM file.
Recommend updating the POM file to reference Maven version 1.8 and place a note in the build procedure stating the required Maven version for the library.

**Comment by vossjannik** [comment]
Hi @robertsonj3,

thank you for your feedback.
You are correct, Maven 3.9+ requires JDK 8 or above to execute.

Your issue should be resolved by 9b970de1c36df58a7a5da3864b5f0a068fbdf760

Best Regards, Jannik Voss
